version: "4.0.0-alpha.3" # x-release-please-version
appVersion: "4.0.0-alpha.3" # x-release-please-version
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "true"
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - kind: changed
      description: '**metrics:** new gates ; fixed labels ; better promql snippets ;  cardinality
        clarification'
      links:
      - name: GitHub commit
        url: https://github.com/enix/x509-certificate-exporter/commit/c28eb69fdac472b49f9a972fd0f808958d9409d7
  artifacthub.io/links: |
    - name: Chart Sources
      url: https://github.com/enix/x509-certificate-exporter/tree/master/deploy/charts/x509-certificate-exporter
    - name: Application Sources
      url: https://github.com/enix/x509-certificate-exporter
    - name: Helm Repository
      url: https://charts.enix.io
    - name: Grafana Dashboard
      url: https://grafana.com/grafana/dashboards/13922

apiVersion: v2
name: x509-certificate-exporter
type: application
description: A Prometheus exporter for certificates focusing on expiration monitoring
keywords:
  - prometheus
  - exporter
  - certificate
  - expiration
home: https://github.com/enix/x509-certificate-exporter
icon: https://github.githubassets.com/images/icons/emoji/unicode/1f50f.png
sources:
  - https://github.com/enix/x509-certificate-exporter
maintainers:
  - name: Enix
    email: contact@enix.fr
    url: https://github.com/enix
  - name: Thibault Vincent
    email: root@devcat.org
    url: https://github.com/npdgm
