# when bumping version, please:
# - replace the "changes" annotation with new content
# - update "containsSecurityUpdates" if needed
version: 1.19.0
appVersion: 2.12.1
annotations:
  artifacthub.io/containsSecurityUpdates: 'true'
  artifacthub.io/prerelease: 'false'
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - "Now watch certificates in the `ca.crt` key of Kubernetes Secrets by default ; upgrading could raise new alerts on existing deployments (ie: for Let's Encrypt legacy chain), unless value `secretTypes` was set"
    - "exporter: fix Kubernetes Secrets selection with duplicated types"
    - "exporter: new build resolves security scan alerts for app dependencies and container base image"
  artifacthub.io/links: |
    - name: Chart Sources
      url: https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
    - name: Application Sources
      url: https://github.com/enix/x509-certificate-exporter
    - name: Helm Repository
      url: https://charts.enix.io
    - name: Grafana Dashboard
      url: https://grafana.com/grafana/dashboards/13922

apiVersion: v2
name: x509-certificate-exporter
type: application
description: A Prometheus exporter for certificates focusing on expiration monitoring
keywords:
  - prometheus
  - exporter
  - certificate
  - expiration
home: https://github.com/enix/x509-certificate-exporter
icon: https://github.githubassets.com/images/icons/emoji/unicode/1f50f.png
sources:
  - https://github.com/enix/x509-certificate-exporter
  - https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
maintainers:
  - name: Enix
    email: contact@enix.fr
    url: https://github.com/enixsas
  - name: Thibault Vincent
    email: root@paraneko.org
    url: https://github.com/npdgm
  - name: Arthur Chaloin
    email: arthur.chaloin@enix.fr
