{{- with .Values.hostPathsExporter.daemonSets }}
{{- range $dsName, $dsDef := . }}
{{- $extraVolumes := concat (dig "extraVolumes" $.Values.hostPathsExporter.extraVolumes $dsDef) $.Values.extraVolumes }}
{{- $extraVolumeMounts := concat (dig "extraVolumeMounts" $.Values.hostPathsExporter.extraVolumeMounts $dsDef) $.Values.extraVolumeMounts }}
{{- $extraEnvs := concat (default (list) $.Values.hostPathsExporter.env) (default (list) $dsDef.env) }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- with (dig "annotations" $.Values.hostPathsExporter.annotations $dsDef) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ printf "%s-%s" (include "x509-certificate-exporter.fullname" $) $dsName }}
  namespace: {{ include "x509-certificate-exporter.namespace" $ }}
  labels:
    {{- include "x509-certificate-exporter.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ printf "host-%s" $dsName }}
spec:
  selector:
    matchLabels:
      {{- include "x509-certificate-exporter.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ printf "host-%s" $dsName }}
  {{- $rl := $.Values.hostPathsExporter.revisionHistoryLimit }}
  {{- if not (kindIs "invalid" $dsDef.revisionHistoryLimit) }}
  {{- $rl = $dsDef.revisionHistoryLimit }}
  {{- end }}
  {{- if not (kindIs "invalid" $rl) }}
  revisionHistoryLimit: {{ int $rl }}
  {{- end }}
  {{- with (dig "updateStrategy" $.Values.hostPathsExporter.updateStrategy $dsDef) }}
  updateStrategy:
    {{- . | toYaml | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "x509-certificate-exporter.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ printf "host-%s" $dsName }}
        {{- with $.Values.podExtraLabels }}
        {{- . | toYaml | trim | nindent 8 }}
        {{- end }}
        {{- with (dig "podExtraLabels" $.Values.hostPathsExporter.podExtraLabels $dsDef) }}
        {{- . | toYaml | trim | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        {{- with mustMerge (dig "podAnnotations" $.Values.hostPathsExporter.podAnnotations $dsDef) $.Values.podAnnotations }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
        {{- if $.Values.webConfiguration }}
        checksum/webconfig: {{ include (print $.Template.BasePath "/webconfig.secret.yaml") $ | sha256sum }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "x509-certificate-exporter.hostPathsExporterServiceAccountName" $ }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
      {{- with (dig "affinity" $.Values.hostPathsExporter.affinity $dsDef) }}
      affinity:
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
      {{- with (dig "tolerations" $.Values.hostPathsExporter.tolerations $dsDef) }}
      tolerations:
      {{- . | toYaml | trim | nindent 6 }}
      {{- end }}
      {{- with (dig "podSecurityContext" $.Values.hostPathsExporter.podSecurityContext $dsDef) }}
      securityContext:
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
      {{- with (dig "nodeSelector" $.Values.hostPathsExporter.nodeSelector $dsDef) }}
      nodeSelector:
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
      restartPolicy: {{ dig "restartPolicy" $.Values.hostPathsExporter.restartPolicy $dsDef }}
      {{- with default $.Values.priorityClassName (dig "priorityClassName" $.Values.hostPathsExporter.priorityClassName $dsDef) }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
      - name: {{ $.Chart.Name }}
        {{- with (dig "securityContext" $.Values.hostPathsExporter.securityContext $dsDef) }}
        securityContext:
          {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
        {{- with (dig "resources" $.Values.hostPathsExporter.resources $dsDef) }}
        resources:
          {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
        image: {{ include "x509-certificate-exporter.image" $ }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- if $extraEnvs }}
        env:
        {{- toYaml $extraEnvs | trim | nindent 8 }}
        {{- end }}
        args:
        - --config=/etc/x509-certificate-exporter/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/x509-certificate-exporter
          readOnly: true
        {{- range dig "watchDirectories" $.Values.hostPathsExporter.watchDirectories $dsDef }}
        - name: dir-{{ . | clean | sha1sum }}
          mountPath: /mnt/watch/dir-{{ . | clean | sha1sum }}/{{ . | clean }}
          readOnly: true
        {{- end }}
        {{- range dig "watchSpecificExtensionDirectories" $.Values.hostPathsExporter.watchSpecificExtensionDirectories $dsDef }}
        - name: dir-{{ .directory| clean | sha1sum }}
          mountPath: /mnt/watch/dir-{{ .directory | clean | sha1sum }}/{{ .directory | clean | dir }}
          readOnly: true
        {{- end }}
        {{- range dig "watchFiles" $.Values.hostPathsExporter.watchFiles $dsDef }}
        - name: file-{{ . | clean | sha1sum }}
          mountPath: /mnt/watch/file-{{ . | clean | sha1sum }}{{ . | clean | dir }}
          readOnly: true
        {{- end }}
        {{- range dig "watchKubeconfFiles" $.Values.hostPathsExporter.watchKubeconfFiles $dsDef }}
        - name: kube-{{ . | clean | sha1sum }}
          mountPath: /mnt/watch/kube-{{ . | clean | sha1sum }}{{ . | clean | dir }}
          readOnly: true
        {{- end }}
        {{- if or $.Values.webConfiguration $.Values.webConfigurationExistingSecret }}
        - name: web-configuration
          mountPath: /mnt/
          readOnly: true
        {{- end }}
        {{- range $extraVolumeMounts }}
        - {{ tpl (. | toYaml) $ | indent 10 | trim }}
        {{- end }}
      {{- if not $.Values.rbacProxy.enabled }}
        ports:
        - name: metrics
          containerPort: {{ $.Values.podListenPort }}
        readinessProbe:
        {{- with omit $.Values.hostPathsExporter.readinessProbe "httpGet" }}
          {{ tpl (. | toYaml) $ | indent 10 | trim }}
        {{- end }}
          httpGet:
            path: /healthz
            port: metrics
          {{- with $.Values.hostPathsExporter.readinessProbe.httpGet }}
            {{ tpl (. | toYaml) $ | indent 12 | trim }}
          {{- end }}
        livenessProbe:
        {{- with omit $.Values.hostPathsExporter.livenessProbe "httpGet" }}
          {{ tpl (. | toYaml) $ | indent 10 | trim }}
        {{- end }}
          httpGet:
            path: /healthz
            port: metrics
          {{- with $.Values.hostPathsExporter.livenessProbe.httpGet }}
            {{ tpl (. | toYaml) $ | indent 12 | trim }}
          {{- end }}
      {{- else }}
      - name: kube-rbac-proxy
        {{- with $.Values.rbacProxy.securityContext }}
        securityContext:
          {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        image: {{ include "x509-certificate-exporter.rbacProxy.image" $ }}
        imagePullPolicy: {{ $.Values.rbacProxy.image.pullPolicy }}
        args:
        - --logtostderr
        - -v=99
        - --upstream=http://[127.0.0.1]:{{ $.Values.rbacProxy.upstreamListenPort }}
        - --secure-listen-address=[$(IP)]:{{ $.Values.podListenPort }}
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: metrics
          containerPort: {{ $.Values.podListenPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: metrics
        {{- with omit $.Values.hostPathsExporter.readinessProbe "httpGet" }}
          {{ tpl (. | toYaml) $ | indent 10 | trim }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
        {{- with omit $.Values.hostPathsExporter.livenessProbe "httpGet" }}
          {{ tpl (. | toYaml) $ | indent 10 | trim }}
        {{- end }}
        {{- with $.Values.rbacProxy.resources }}
        resources:
        {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
      {{- end }}
      hostNetwork: {{ $.Values.hostNetwork }}
      volumes:
      - name: config
        configMap:
          name: {{ printf "%s-%s" (include "x509-certificate-exporter.fullname" $) $dsName }}
      {{- $hostPathType := $.Values.hostPathsExporter.hostPathVolumeType }}
      {{- if hasKey $dsDef "hostPathVolumeType" }}
        {{- $hostPathType = $dsDef.hostPathVolumeType }}
      {{- end }}
      {{- range dig "watchDirectories" $.Values.hostPathsExporter.watchDirectories $dsDef }}
      - name: dir-{{ . | clean | sha1sum }}
        hostPath:
          path: {{ . | clean }}
          {{- if $hostPathType }}
          type: {{ $hostPathType | quote }}
          {{- end }}
      {{- end }}
      {{- range dig "watchSpecificExtensionDirectories" $.Values.hostPathsExporter.watchSpecificExtensionDirectories $dsDef }}
      - name: dir-{{ .directory | clean | sha1sum }}
        hostPath:
          path: {{ .directory | clean }}
          {{- if $hostPathType }}
          type: {{ $hostPathType | quote }}
          {{- end }}
      {{- end }}
      {{- range dig "watchFiles" $.Values.hostPathsExporter.watchFiles $dsDef }}
      - name: file-{{ . | clean | sha1sum }}
        hostPath:
          path: {{ . | clean | dir }}
          {{- if $hostPathType }}
          type: {{ $hostPathType | quote }}
          {{- end }}
      {{- end }}
      {{- range dig "watchKubeconfFiles" $.Values.hostPathsExporter.watchKubeconfFiles $dsDef }}
      - name: kube-{{ . | clean | sha1sum }}
        hostPath:
          path: {{ . | clean | dir }}
          {{- if $hostPathType }}
          type: {{ $hostPathType | quote }}
          {{- end }}
      {{- end }}
      {{- if or $.Values.webConfiguration $.Values.webConfigurationExistingSecret }}
      - name: web-configuration
        secret:
          secretName: "{{ default (include "x509-certificate-exporter.webConfigurationSecretName" $) $.Values.webConfigurationExistingSecret }}"
          items:
          - key: webconfig.yaml
            path: webconfig.yaml
      {{- end }}
      {{- range $extraVolumes }}
      - {{ tpl (. | toYaml) $ | indent 8 | trim }}
      {{- end }}
{{- end }}
{{- end }}
