{{- if .Values.prometheusRules.create }}
{{- $rulePrefix:= .Values.prometheusRules.rulePrefix }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "x509-certificate-exporter.fullname" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusRules.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  groups:
  {{- if .Values.prometheusRules.disableBuiltinAlertGroup }}
    {{- if not (len .Values.prometheusRules.extraAlertGroups) }}
      {{ fail "Extra alert groups (extraAlertGroups) are required when disableBuiltinAlertGroup is set!" }}
    {{- end }}
  {{- else }}
  - name: x509-certificate-exporter.rules
    rules:
    {{- if .Values.prometheusRules.alertOnReadErrors }}
    - alert: '{{ printf "%s %s" $rulePrefix "X509ExporterReadErrors" | trim }}'
      expr: delta(x509_read_errors[15m]) > 0
      for: 5m
      labels:
        severity: {{ .Values.prometheusRules.readErrorsSeverity }}
        {{- if .Values.prometheusRules.alertExtraLabels }}
        {{- toYaml .Values.prometheusRules.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: Increasing read errors for x509-certificate-exporter
        description: Over the last 15 minutes, this x509-certificate-exporter instance has experienced errors reading certificate files or querying the Kubernetes API. This could be caused by a misconfiguration if triggered when the exporter starts.
    {{- end }}
    {{- if .Values.prometheusRules.alertOnCertificateErrors }}
    - alert: '{{ printf "%s %s" $rulePrefix "CertificateError" | trim }}'
      expr: x509_cert_error > 0
      for: 15m
      labels:
        severity: {{ .Values.prometheusRules.certificateErrorsSeverity }}
        {{- if .Values.prometheusRules.alertExtraLabels }}
        {{- toYaml .Values.prometheusRules.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: Certificate cannot be decoded
        description: Certificate could not be decoded {{ "{{if" }} $labels.secret_name {{ "}}" }}in Kubernetes secret "{{ "{{" }} $labels.secret_namespace {{ "}}" }}/{{ "{{" }} $labels.secret_name {{ "}}" }}"{{ "{{else}}" }}at location "{{ "{{" }} $labels.filepath {{ "}}" }}"{{ "{{end}}" }}
    {{- end }}
    - alert: '{{ printf "%s %s" $rulePrefix "CertificateRenewal" | trim }}'
      expr: ((x509_cert_not_after - time()) / 86400) < {{ .Values.prometheusRules.warningDaysLeft }}
      for: 15m
      labels:
        severity: {{ .Values.prometheusRules.certificateRenewalsSeverity }}
        {{- if .Values.prometheusRules.alertExtraLabels }}
        {{- toYaml .Values.prometheusRules.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: Certificate should be renewed
        description: Certificate for "{{ "{{" }} $labels.subject_CN {{ "}}" }}" should be renewed {{ "{{if" }} $labels.secret_name {{ "}}" }}in Kubernetes secret "{{ "{{" }} $labels.secret_namespace {{ "}}" }}/{{ "{{" }} $labels.secret_name {{ "}}" }}"{{ "{{else}}" }}at location "{{ "{{" }} $labels.filepath {{ "}}" }}"{{ "{{end}}" }}
    - alert: '{{ printf "%s %s" $rulePrefix "CertificateExpiration" | trim }}'
      expr: ((x509_cert_not_after - time()) / 86400) < {{ .Values.prometheusRules.criticalDaysLeft }}
      for: 15m
      labels:
        severity: {{ .Values.prometheusRules.certificateExpirationsSeverity }}
        {{- if .Values.prometheusRules.alertExtraLabels }}
        {{- toYaml .Values.prometheusRules.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: Certificate is about to expire
        description: Certificate for "{{ "{{" }} $labels.subject_CN {{ "}}" }}" is about to expire {{ "{{if" }} $labels.secret_name {{ "}}" }}in Kubernetes secret "{{ "{{" }} $labels.secret_namespace {{ "}}" }}/{{ "{{" }} $labels.secret_name {{ "}}" }}"{{ "{{else}}" }}at location "{{ "{{" }} $labels.filepath {{ "}}" }}"{{ "{{end}}" }}
  {{- end }}
{{- range .Values.prometheusRules.extraAlertGroups }}
  - {{ tpl (toYaml .) $ | indent 4 | trim }}
{{- end }}
{{- end }}
