{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "x509-certificate-exporter.fullname" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- if .Values.prometheusRules.extraLabels }}
    {{- toYaml .Values.prometheusRules.extraLabels | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.prometheusRules.rules }}
  groups:
    - name: {{ printf "%s.rules" (include "x509-certificate-exporter.name" $) }}
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
  {{- end }}
{{- end }}
