{{- if .Values.rbac.create }}
{{- if .Values.secretsExporter.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "x509-certificate-exporter.secretsExporterServiceAccountName" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
{{- with .Values.rbac.secretsExporter.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.hostPathsExporter.daemonSets }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "x509-certificate-exporter.hostPathsExporterServiceAccountName" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
{{- with .Values.rbac.hostPathsExporter.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
