{{- if .Values.rbac.create }}
{{- if .Values.secretsExporter.enabled }}
---
apiVersion: {{ include "capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "x509-certificate-exporter.secretsExporterClusterRoleBindingName" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
{{- with .Values.rbac.secretsExporter.clusterRoleBindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "x509-certificate-exporter.secretsExporterClusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "x509-certificate-exporter.secretsExporterServiceAccountName" . }}
  namespace: {{ include "x509-certificate-exporter.namespace" . }}
{{- end }}
{{- if .Values.hostPathsExporter.daemonSets }}
---
apiVersion: {{ include "capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "x509-certificate-exporter.hostPathsExporterClusterRoleBindingName" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
  {{- with .Values.rbac.hostPathsExporter.clusterRoleBindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "x509-certificate-exporter.hostPathsExporterClusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "x509-certificate-exporter.hostPathsExporterServiceAccountName" . }}
  namespace: {{ include "x509-certificate-exporter.namespace" . }}
{{- end }}
{{- end }}
