{{- $extraVolumes := concat .Values.secretsExporter.extraVolumes .Values.extraVolumes }}
{{- $extraVolumeMounts := concat .Values.secretsExporter.extraVolumeMounts .Values.extraVolumeMounts }}
{{- if .Values.secretsExporter.enabled }}
apiVersion: {{ include "capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "x509-certificate-exporter.secretsExporterName" . }}
  namespace: {{ include "x509-certificate-exporter.namespace" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "x509-certificate-exporter.selectorLabels" . | nindent 6 }}
  {{- with .Values.secretsExporter.replicas }}
  replicas: {{ . }}
  {{- end }}
  {{- with .Values.secretsExporter.strategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "x509-certificate-exporter.labels" . | nindent 8 }}
        {{- with .Values.podExtraLabels }}
        {{- . | toYaml | trim | nindent 8 }}
        {{- end }}
        {{- with .Values.secretsExporter.podExtraLabels }}
        {{- . | toYaml | trim | nindent 8 }}
        {{- end }}
      {{- if or (or .Values.podAnnotations .Values.secretsExporter.podAnnotations) .Values.webConfiguration }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
        {{- with .Values.secretsExporter.podAnnotations }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
        {{- if .Values.webConfiguration }}
        checksum/config: {{ include (print .Template.BasePath "/webconfig.secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.secretsExporter.affinity }}
      affinity:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.secretsExporter.tolerations }}
      tolerations:
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- with .Values.secretsExporter.podSecurityContext }}
      securityContext:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.secretsExporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.secretsExporter.restartPolicy }}
      serviceAccountName: {{ include "x509-certificate-exporter.secretsExporterServiceAccountName" . }}
      {{- with default .Values.priorityClassName .Values.secretsExporter.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.secretsExporter.securityContext }}
        securityContext:
          {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        {{- with .Values.secretsExporter.resources }}
        resources:
          {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
        image: {{ include "x509-certificate-exporter.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if or $extraVolumes .Values.webConfiguration .Values.webConfigurationExistingSecret }}
        volumeMounts:
        {{- range $extraVolumeMounts }}
        - {{ tpl (. | toYaml) $ | indent 10 | trim }}
        {{- end }}
        {{- if or .Values.webConfiguration .Values.webConfigurationExistingSecret }}
        - name: web-configuration
          mountPath: /mnt/
          readOnly: true
        {{- end }}
        {{- end }}
        {{- if .Values.secretsExporter.env }}
        env:
        {{- toYaml .Values.secretsExporter.env | trim | nindent 8 }}
        {{- end }}
        args:
        {{- if .Values.secretsExporter.debugMode }}
        - --debug
        {{- end }}
        {{- if $.Values.exposeRelativeMetrics }}
        - --expose-relative-metrics
        {{- end }}
        - --watch-kube-secrets
        {{- range .Values.secretsExporter.secretTypes }}
        - --secret-type={{ .type | trim }}:{{ .key | trim }}
        {{- end }}
        {{- range .Values.secretsExporter.includeNamespaces }}
        - --include-namespace={{ . | trim }}
        {{- end }}
        {{- range .Values.secretsExporter.excludeNamespaces }}
        - --exclude-namespace={{ . | trim }}
        {{- end }}
        {{- range .Values.secretsExporter.includeLabels }}
        - --include-label={{ . | trim }}
        {{- end }}
        {{- range .Values.secretsExporter.excludeLabels }}
        - --exclude-label={{ . | trim }}
        {{- end }}
        {{- if not (kindIs "invalid" .Values.metricLabelsFilterList) }}
        - --expose-labels={{ .Values.metricLabelsFilterList | join "," }}
        {{- end }}
        {{- if .Values.secretsExporter.cache.enabled }}
        - --max-cache-duration={{ .Values.secretsExporter.cache.maxDuration | int }}s
        {{- else }}
        - --max-cache-duration=0
        {{- end }}
        {{- with .Values.secretsExporter.kubeApiRateLimits }}
          {{- if .enabled }}
        - --kube-api-rate-limit-qps={{ int .queriesPerSecond }}
        - --kube-api-rate-limit-burst={{ int .burstQueries }}
          {{- end }}
        {{- end }}
        {{- if .Values.exposePerCertificateErrorMetrics }}
        - --expose-per-cert-error-metrics
        {{- end }}
        {{- if or .Values.webConfiguration .Values.webConfigurationExistingSecret }}
        - --web.config.file=/mnt/webconfig.yaml
        {{- end }}
      {{- if not .Values.rbacProxy.enabled }}
        - --listen-address=:{{ .Values.podListenPort }}
        ports:
        - name: metrics
          containerPort: {{ .Values.podListenPort }}
      {{- else }}
        - --listen-address=:{{ .Values.rbacProxy.upstreamListenPort }}
      - name: kube-rbac-proxy
        {{- with .Values.rbacProxy.securityContext }}
        securityContext:
          {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        image: {{ include "x509-certificate-exporter.rbacProxy.image" . }}
        imagePullPolicy: {{ .Values.rbacProxy.imagePullPolicy }}
        args:
        - --logtostderr
        - -v=99
        - --upstream=http://[127.0.0.1]:{{ .Values.rbacProxy.upstreamListenPort }}
        - --secure-listen-address=[$(IP)]:{{ .Values.podListenPort }}
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: metrics
          containerPort: {{ .Values.podListenPort }}
        {{- with .Values.rbacProxy.resources }}
        resources:
        {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if or $extraVolumes .Values.webConfiguration .Values.webConfigurationExistingSecret }}
      volumes:
      {{- range $extraVolumes }}
      - {{ tpl (. | toYaml) $ | indent 8 | trim }}
      {{- end }}
      {{- if or .Values.webConfiguration .Values.webConfigurationExistingSecret }}
      - name: web-configuration
        secret:
          secretName: "{{ default (include "x509-certificate-exporter.webConfigurationSecretName" .) .Values.webConfigurationExistingSecret }}"
          items:
          - key: webconfig.yaml
            path: webconfig.yaml
      {{- end }}
      {{- end }}
{{- end }}
