{{- if .Values.prometheusPodMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "x509-certificate-exporter.fullname" . }}-podmonitor
  namespace: {{ include "x509-certificate-exporter.namespace" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusPodMonitor.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "x509-certificate-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
    interval: {{ .Values.prometheusPodMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.prometheusPodMonitor.scrapeTimeout }}
    {{- if .Values.rbacProxy.enable }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    {{- end }}
    {{- with .Values.prometheusPodMonitor.metricRelabelings }}
    metricRelabelings:
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- with .Values.prometheusPodMonitor.relabelings }}
    relabelings:
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
