{{- if .Values.prometheusServiceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "x509-certificate-exporter.fullname" . }}
  namespace: {{ include "x509-certificate-exporter.namespace" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusServiceMonitor.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "x509-certificate-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.prometheusServiceMonitor.scrapeTimeout }}
    {{- if .Values.rbacProxy.enable }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    {{- end }}
    {{- with .Values.prometheusServiceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- with .Values.prometheusServiceMonitor.relabelings }}
    relabelings:
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
