name: Packaging

on:
  pull_request:
    paths:
      - deploy/charts/**

jobs:
  chart-testing:
    name: Chart Testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      # FIXME
      #- name: Run chart-testing (list-changed)
      #  id: list-changed
      #  run: |
      #    set -euo pipefail
      #    changed=$(ct list-changed --chart-dirs deploy/charts --target-branch ${{ github.base_ref }})
      #    if [[ -n "$changed" ]]; then
      #      echo "::set-output name=changed::true"
      #    fi

      - name: Run chart-testing (lint)
        run: |
          set -euo pipefail
          ct lint --chart-dirs deploy/charts --target-branch ${{ github.base_ref }} \
            --validate-maintainers=false --check-version-increment=false 

      # FIXME
      #- name: Create KinD cluster
      #  uses: engineerd/setup-kind@v0.5.0
      #  with:
      #    version: v0.15.0
      #  if: steps.list-changed.outputs.changed == 'true'

      # FIXME
      #- name: Run chart-testing (install)
      #  run: |
      #    set -euo pipefail
      #    ct install --chart-dirs deploy/charts
