name: Release
on:
  push:

concurrency: 
  group: release/${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  semver:
    name: Semantic Version
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.dry-run.outputs.new_release_published }}
      version: ${{ steps.dry-run.outputs.new_release_version }}
      major: ${{ steps.dry-run.outputs.new_release_major_version }}
      minor: ${{ steps.dry-run.outputs.new_release_minor_version }}
      patch: ${{ steps.dry-run.outputs.new_release_patch_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Semantic Release (dry-run)
        id: dry-run
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          # FIXME
          branch: github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

  stuff:
    needs:
      - semver
    strategy:
      matrix:
        file: [a.txt, b.txt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: repository

      - name: Create directory
        run: |
          mkdir builds

      - name: Create file
        run: |
          echo "${{ needs.semver.outputs.version }}" > builds/${{ matrix.file }}

      - name: Archive file
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: builds/*
          retention-days: 2

  release:
    name: Semantic Release
    needs:
      - stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: repository
          persist-credentials: false

      - name: Retrieve all builds
        uses: actions/download-artifact@v3
        with:
          name: builds
          path: builds

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          working_directory: repository
          dry_run: true
          # FIXME
          branch: github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
